services:

  mqtt:
    container_name: raven-eye-mqtt
    build:
      context: .
      dockerfile: ./docker/mosquitto/Dockerfile
    ports:
      - "1883:1883"
    environment:
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    volumes:
      - ./docker/mosquitto:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log

  fastapi:
    container_name: raven-eye-fastapi
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - mqtt

  frontend:
    container_name: raven-eye-frontend
    command: /run.sh
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - ./docker/frontend/run.sh:/run.sh

  web:
    container_name: raven-eye-web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/app:ro
    depends_on:
      - fastapi