services:

  mqtt:
    container_name: fpv-mqtt
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto:/mosquitto/config
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log

  scanner_emulator:
    image: python:3.13-slim
    container_name: fpv-scanner-emulator
    command: /run.sh
    volumes:
      - ./scanner_emulator:/app
      - ./docker/scanner_emulator/run.sh:/run.sh
    depends_on:
      - mqtt

  fastapi:
    container_name: fpv-fastapi
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - mqtt

  frontend:
    container_name: fpv-frontend
    command: /run.sh
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - ./docker/frontend/run.sh:/run.sh

  web:
    container_name: fpv-web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/app:ro
    depends_on:
      - fastapi